var cry = [
  "<span>help</span>",
  "i'm tired",
  "I don't want to keep going",
  "why am i <p>alive</p>",
  "i can't keep paying for this",
  "please someone hold me",
  "please someone keep me safe for once",
  "i'm tired of fighting for someone",
  "i'm in a hell of <span>my own making</span>",
  "help me <p>help me</p>",
  "please keep me safe",
  "what even is <span>comfort</span>",
  "i dont know what <span>comfort</span> is",
  "i'm <p>scared</p> i'm <p>scared</p>",
  "i'm too used to <p>panic</p> it feels like a <p>second nature</p>",
  "please please please please",
  "i can't see a <p>way out</p> other than death",
  "<p>selfish piece of shit</p>",
  "i'm tired of giving something i also <p>need</p>",
  "i don't have anything left to <p>give</p>",
  "why do you <p>take</p> from me",
  "how long do i have to endure",
  "<p>catastrophes</p> waiting around every corner",
  "why can't i have more",
  "don't i deserve more after everything",
  "i'm tired of wanting",
  "i'm tired of hoping and longing",
  // "oah['oeha['oehaohea[oerhaoerhoerhjew;nofjn;aowg[owrho[hg[rh['[iwj'pdawe'awegh'aiweg'awiejgpiweapin'asergie[j",
  // "<p>kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me kill me </p>",
];
var what_i_deserve=[
  "i'm a <p>scum</p>",
  "why am i like this",
  "<p>i deserve to be dead</p>",
  "<p>i deserve to be in hell</p>",
  "useless piece of shit",
  "why can't your fucking <p>keep your mouth shut</p>",
  "you <p>ruin everything</p> whenever you open your mouth",
  "why the fuck won't you comfort her",
  "you are <p>weak</p>",
  "don't pretend like you are strong",
  "you are <p>too weak</p> to end this",
  "you are <p>too scared</p>",
  "you don't know shit",
  "you do fuck all for anyone",
  "and <p>blame everything</p> else for your shit",
  "that's why you'll always be alone",
  "that's why no one will <p>take you seriously</p>",
  "that's why you will never grow up",
  "you are too much of a pussy to do anything",
  "and too much of a scum to keep your mouth shut",
  "and when you see opportunity you turn into your fucking <p>mom</p>",
  "and try to <p>weaponize guilt</p>",
  "you <p>disgust</p> me",
  "<p>i hate you</p> more then anyone else in the world",
  "useless piece of shit",
  "I'm never <p>enough</p> am I"
]

var question = [
  "why did you <p>abandon</p> your kid",
  "why the fuck did think its good to <p>kill</p> your own kid",
  "why won't you ever take my <p>anger</p> seriously",
  "why did you threaten your <p>suicidal kid</p> with homelessness",
  "i cried,begged and clung to your leg <p>not to leave</p> ",
  "you <p>asked me</p> to bring a razer blade for us to <p>kill ourselves</p>",
  "why didn't you <p>love me unconditionally</p>",
  "why did you even give birth to me",
];

var hope = [
  "I want to go to vacation",
  "I wish everyone around me were safe",
  "its nice to talk to people i'm comfortable with",
  "I want to feel hopeful with someone",
];
